const Contact = () => {
      return (
          <section id="contact" className="py-16 px-6">
                <div className="max-w-3xl mx-auto text-center">
                        <h2 className="text-3xl font-bold mb-3 text-white">
                                  Get In Touch
                                          </h2>
                                                  <p className="text-gray-500 mb-10 text-sm">
                                                            Open to new opportunities and collaborations!
                                                                    </p>

                                                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-12 text-left">
                                                                                      {[
                                                                                                  {
                                                                                                                label: 'Email',
                                                                                                                              value: 'aanchal.07a@gmail.com',
                                                                                                                                            href: 'mailto:aanchal.07a@gmail.com',
                                                                                                                                                        },
                                                                                                                                                                    {
                                                                                                                                                                                  label: 'LinkedIn',
                                                                                                                                                                                                value: 'linkedin.com/in/aanchalk07',
                                                                                                                                                                                                              href: 'https://www.linkedin.com/in/aanchalk07',
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                    label: 'GitHub',
                                                                                                                                                                                                                                                                  value: 'github.com/aanchalk123',
                                                                                                                                                                                                                                                                                href: 'https://github.com/aanchalk123',
                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                      label: 'Phone',
                                                                                                                                                                                                                                                                                                                                    value: '+91 6204035208',
                                                                                                                                                                                                                                                                                                                                                  href: 'tel:+916204035208',
                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                        ].map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                  key={c.label}
                                                                                                                                                                                                                                                                                                                                                                                                                href={c.href}
                                                                                                                                                                                                                                                                                                                                                                                                                              target={c.href.startsWith('http') ? '_blank' : undefined}
                                                                                                                                                                                                                                                                                                                                                                                                                                            rel="noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex flex-col gap-1 bg-[#0d1b2a] hover:bg-[#112240] rounded-xl p-4 transition-all duration-200"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs text-gray-500">{c.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-sm text-gray-300">{c.value}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-600 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  © 2025 Aanchal Kumari · Built with React.js & Tailwind CSS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Contact
