const Experience = () => {
      return (
          <section id="experience" className="py-16 px-6">
                <div className="max-w-3xl mx-auto">
                        <h2 className="text-3xl font-bold text-center mb-10 text-white">
                                  Experience & Education
                                          </h2>

                                                  <div className="flex flex-col gap-4">
                                                            {/* Experience */}
                                                                      <div className="bg-[#0d1b2a] rounded-xl p-5">
                                                                                  <div className="flex flex-wrap items-start justify-between gap-2 mb-4">
                                                                                                <div>
                                                                                                                <p className="text-xs text-gray-500 uppercase tracking-widest mb-1">Work Experience</p>
                                                                                                                                <h3 className="text-white font-semibold text-base">
                                                                                                                                                  Frontend Developer Intern & Trainee
                                                                                                                                                                  </h3>
                                                                                                                                                                                  <p className="text-gray-500 text-sm mt-0.5">
                                                                                                                                                                                                    ETECHCUBE LLP · Jamshedpur, Jharkhand
                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                <span className="text-xs text-gray-400 bg-white/5 px-3 py-1 rounded-full shrink-0">
                                                                                                                                                                                                                                                                Dec 2024 – Dec 2025
                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                      <ul className="space-y-2">
                                                                                                                                                                                                                                                                                                                    {[
                                                                                                                                                                                                                                                                                                                                    'Built responsive and dynamic user interfaces using React.js',
                                                                                                                                                                                                                                                                                                                                                    'Collaborated with backend teams for REST API integration',
                                                                                                                                                                                                                                                                                                                                                                    'Improved UI/UX and developed reusable component architecture',
                                                                                                                                                                                                                                                                                                                                                                                    'Worked with Git and real-world project workflows',
                                                                                                                                                                                                                                                                                                                                                                                                    'Contributed to development of client-facing modules using React.js',
                                                                                                                                                                                                                                                                                                                                                                                                                  ].map((point) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <li key={point} className="flex items-start gap-2 text-gray-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-gray-600 mt-0.5 shrink-0">→</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {point}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Education */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-[#0d1b2a] rounded-xl p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-wrap items-start justify-between gap-2 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-500 uppercase tracking-widest mb-1">Education</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-white font-semibold text-base">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Bachelor's of Computer Application
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-500 text-sm mt-0.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Jamshedpur Women's University · 80.87%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs text-gray-400 bg-white/5 px-3 py-1 rounded-full shrink-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Aug 2022 – Aug 2025
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-start gap-2 text-gray-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-gray-600 mt-0.5 shrink-0">→</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Final Year Project: Hospital Management System
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Experience
