const Hero = () => {
      return (
          <section className="min-h-screen flex flex-col justify-center items-center text-center px-6 pt-24 relative overflow-hidden">
                {/* Background glow blobs */}
                      <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none" />
                            <div className="absolute top-2/3 left-1/4 w-[300px] h-[300px] bg-violet-600/10 rounded-full blur-[100px] pointer-events-none" />

                                  <div className="relative z-10 fade-up">
                                          <p className="text-blue-400 text-sm font-medium tracking-widest uppercase mb-4">
                                                    Frontend Developer
                                                            </p>
                                                                    <h1
                                                                              className="text-5xl md:text-7xl font-extrabold mb-4 leading-tight"
                                                                                        style={{ fontFamily: 'Syne, sans-serif' }}
                                                                                                >
                                                                                                          Hi, I'm{' '}
                                                                                                                    <span className="gradient-text">Aanchal Kumari</span>
                                                                                                                            </h1>
                                                                                                                                    <p className="text-gray-400 text-lg md:text-xl mb-10 max-w-xl mx-auto">
                                                                                                                                              I build responsive, clean and user-friendly web interfaces with React.js.
                                                                                                                                                      </p>

                                                                                                                                                              <div className="flex flex-wrap gap-4 justify-center">
                                                                                                                                                                        <a
                                                                                                                                                                                    href="https://github.com/aanchalk123"
                                                                                                                                                                                                target="_blank"
                                                                                                                                                                                                            rel="noreferrer"
                                                                                                                                                                                                                        className="bg-blue-500 hover:bg-blue-600 text-white px-7 py-3 rounded-full font-medium transition-all duration-200 hover:shadow-lg hover:shadow-blue-500/25"
                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                              GitHub
                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                              href="https://www.linkedin.com/in/aanchalk07"
                                                                                                                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                                                                                                                                      rel="noreferrer"
                                                                                                                                                                                                                                                                                                                  className="border border-blue-400/50 text-blue-400 hover:bg-blue-400/10 px-7 py-3 rounded-full font-medium transition-all duration-200"
                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                        LinkedIn
                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                        href="mailto:aanchal.07a@gmail.com"
                                                                                                                                                                                                                                                                                                                                                                                    className="border border-gray-600 text-gray-300 hover:bg-white/5 px-7 py-3 rounded-full font-medium transition-all duration-200"
                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                          Email Me
                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Scroll indicator */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-16 flex flex-col items-center gap-2 text-gray-600 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>Scroll down</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="w-px h-8 bg-gradient-to-b from-gray-600 to-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Hero
