import { useState } from 'react'

const NavBar = () => {
  const [open, setOpen] = useState(false)
    const links = ['Skills', 'Projects', 'Experience', 'Contact']

      return (
          <nav className="fixed top-0 w-full z-50 bg-[#060d17]/80 backdrop-blur-md border-b border-white/5">
                <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
                        <span
                                  className="font-bold text-xl"
                                            style={{ fontFamily: 'Syne, sans-serif' }}
                                                    >
                                                              <span className="text-blue-400">Aanchal</span>
                                                                        <span className="text-white">.</span>
                                                                                </span>

                                                                                        {/* Desktop links */}
                                                                                                <div className="hidden md:flex gap-8 text-sm text-gray-400">
                                                                                                          {links.map((link) => (
                                                                                                                      <a
                                                                                                                                    key={link}
                                                                                                                                                  href={`#${link.toLowerCase()}`}
                                                                                                                                                                className="hover:text-blue-400 transition-colors duration-200"
                                                                                                                                                                            >
                                                                                                                                                                                          {link}
                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                {/* Mobile hamburger */}
                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                  className="md:hidden text-gray-400 hover:text-white"
                                                                                                                                                                                                                                                            onClick={() => setOpen(!open)}
                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                              <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2">
                                                                                                                                                                                                                                                                                          {open ? (
                                                                                                                                                                                                                                                                                                        <path d="M6 18L18 6M6 6l12 12" strokeLinecap="round" />
                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                  <path d="M4 6h16M4 12h16M4 18h16" strokeLinecap="round" />
                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                        </svg>
                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                            {/* Mobile menu */}
                                                                                                                                                                                                                                                                                                                                                                                  {open && (
                                                                                                                                                                                                                                                                                                                                                                                          <div className="md:hidden bg-[#0d1b2a] border-t border-white/5 px-6 py-4 flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                    {links.map((link) => (
                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                              key={link}
                                                                                                                                                                                                                                                                                                                                                                                                                                            href={`#${link.toLowerCase()}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-gray-300 hover:text-blue-400 transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {link}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default NavBar