const projects = [
      {
          title: 'DHTC India',
              description:
                    'Improved dashboard responsiveness across multiple screen sizes. Enhanced functionality by building dynamic UI components and interactive features.',
                        tech: ['React.js', 'CSS', 'Responsive UI'],
                            type: 'Professional',
                              },
                                {
                                    title: 'DHTC Logistics',
                                        description:
                                              'Developed responsive frontend interfaces using React.js and reusable components. Integrated REST APIs and implemented reusable UI components.',
                                                  tech: ['React.js', 'REST APIs', 'Components'],
                                                      type: 'Professional',
                                                        },
                                                          {
                                                              title: 'Calcutta Express Transport Co.',
                                                                  description:
                                                                        'Contributed to frontend development and REST API integration using React.js. Collaborated with cross-functional teams to meet project requirements.',
                                                                            tech: ['React.js', 'REST APIs'],
                                                                                type: 'Professional',
                                                                                  },
                                                                                    {
                                                                                        title: 'Hospital Management System',
                                                                                            description:
                                                                                                  'Final year project — a web-based prototype for managing patient records and appointment scheduling with attention to usability and data accuracy.',
                                                                                                      tech: ['HTML5', 'CSS3', 'JavaScript', 'SQLite3'],
                                                                                                          type: 'Academic',
                                                                                                            },
                                                                                                            ]

                                                                                                            const Projects = () => {
                                                                                                              return (
                                                                                                                  <section id="projects" className="py-24 px-6 bg-[#080f1a]">
                                                                                                                        <div className="max-w-5xl mx-auto">
                                                                                                                                <p className="text-blue-400 text-sm font-medium tracking-widest uppercase text-center mb-3">
                                                                                                                                          What I've built
                                                                                                                                                  </p>
                                                                                                                                                          <h2
                                                                                                                                                                    className="text-4xl font-bold text-center mb-14 text-white"
                                                                                                                                                                              style={{ fontFamily: 'Syne, sans-serif' }}
                                                                                                                                                                                      >
                                                                                                                                                                                                Projects
                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                                                                                                                                                                                                                          {projects.map((project) => (
                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                    key={project.title}
                                                                                                                                                                                                                                                                  className="group bg-[#0d1b2a] border border-white/5 hover:border-blue-500/40 rounded-2xl p-6 transition-all duration-300 hover:shadow-xl hover:shadow-blue-500/5 flex flex-col gap-4"
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                            <div className="flex items-start justify-between gap-2">
                                                                                                                                                                                                                                                                                                            <h3
                                                                                                                                                                                                                                                                                                                              className="text-blue-400 font-semibold text-lg group-hover:text-blue-300 transition-colors"
                                                                                                                                                                                                                                                                                                                                                style={{ fontFamily: 'Syne, sans-serif' }}
                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                  {project.title}
                                                                                                                                                                                                                                                                                                                                                                                                  </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`text-xs px-2 py-1 rounded-full shrink-0 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                        project.type === 'Professional'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'bg-blue-500/15 text-blue-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : 'bg-violet-500/15 text-violet-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {project.type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-400 text-sm leading-relaxed flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {project.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {project.tech.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-xs bg-white/5 text-gray-400 px-3 py-1 rounded-full border border-white/5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Projects
