const projects = [
      {
          title: 'DHTC India',
              description:
                    'Improved dashboard responsiveness across multiple screen sizes. Enhanced functionality by building dynamic UI components and interactive features.',
                        tech: ['React.js', 'CSS', 'Responsive UI'],
                            type: 'Professional',
                              },
                                {
                                    title: 'DHTC Logistics',
                                        description:
                                              'Developed responsive frontend interfaces using React.js and reusable components. Integrated REST APIs and implemented reusable UI components.',
                                                  tech: ['React.js', 'REST APIs', 'Components'],
                                                      type: 'Professional',
                                                        },
                                                          {
                                                              title: 'Calcutta Express Transport Co.',
                                                                  description:
                                                                        'Contributed to frontend development and REST API integration using React.js. Collaborated with cross-functional teams to meet project requirements.',
                                                                            tech: ['React.js', 'REST APIs'],
                                                                                type: 'Professional',
                                                                                  },
                                                                                    {
                                                                                        title: 'Hospital Management System',
                                                                                            description:
                                                                                                  'Final year project — a web-based prototype for managing patient records and appointment scheduling with attention to usability and data accuracy.',
                                                                                                      tech: ['HTML5', 'CSS3', 'JavaScript', 'SQLite3'],
                                                                                                          type: 'Academic',
                                                                                                            },
                                                                                                            ]

                                                                                                            const Projects = () => {
                                                                                                              return (
                                                                                                                  <section id="projects" className="py-16 px-6 bg-[#080f1a]">
                                                                                                                        <div className="max-w-3xl mx-auto">
                                                                                                                                <h2 className="text-3xl font-bold text-center mb-10 text-white">
                                                                                                                                          Projects
                                                                                                                                                  </h2>

                                                                                                                                                          <div className="flex flex-col gap-4">
                                                                                                                                                                    {projects.map((project) => (
                                                                                                                                                                                <div
                                                                                                                                                                                              key={project.title}
                                                                                                                                                                                                            className="group bg-[#0d1b2a] rounded-xl p-5 transition-all duration-300 hover:bg-[#112240] flex flex-col gap-3"
                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                      <div className="flex items-center justify-between gap-2">
                                                                                                                                                                                                                                                      <h3 className="text-white font-semibold text-base">
                                                                                                                                                                                                                                                                        {project.title}
                                                                                                                                                                                                                                                                                        </h3>
                                                                                                                                                                                                                                                                                                        <span
                                                                                                                                                                                                                                                                                                                          className={`text-xs px-2 py-0.5 rounded-full shrink-0 ${
                                                                                                                                                                                                                                                                                                                                              project.type === 'Professional'
                                                                                                                                                                                                                                                                                                                                                                    ? 'bg-blue-500/10 text-blue-400'
                                                                                                                                                                                                                                                                                                                                                                                          : 'bg-violet-500/10 text-violet-400'
                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                              {project.type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-400 text-sm leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {project.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {project.tech.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-xs bg-white/5 text-gray-500 px-2 py-0.5 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Projects
